services:
  - type: web
    name: farmconnect
    env: node
    plan: free
    buildCommand: npm ci && cd client && npm ci && CI=false npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 18.17.0
      - key: CI
        value: false
